# Generated by Django 5.0.3 on 2024-03-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
