# Generated by Django 5.0.3 on 2024-03-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proucts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.TextField(max_length=100, null=True)),
                ('car_brand', models.TextField(max_length=100, null=True)),
                ('car_color', models.TextField(max_length=100, null=True)),
                ('rent_charge', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelTable(
            name='sellerregistration',
            table='seller',
        ),
    ]
