# Generated by Django 5.0.3 on 2024-03-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_proucts_alter_sellerregistration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellerregistration',
            table=None,
        ),
    ]
