# Generated by Django 5.0.3 on 2024-03-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_sellerregistration_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proucts',
            new_name='Products',
        ),
    ]
