# Generated by Django 5.0.3 on 2024-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_rename_proucts_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
