# Generated by Django 5.0.3 on 2024-03-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
