# Generated by Django 5.0.3 on 2024-03-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='capacity',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='seats',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='topspeed',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
