# Generated by Django 5.0.3 on 2024-03-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_products_capacity_products_seats_products_topspeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='seats',
            new_name='fuels',
        ),
    ]
