# Generated by Django 5.0.3 on 2024-03-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rename_seats_products_fuels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
